chatbot/chatbot/chatterbot/ext/django_chatterbot/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import ChatterBotView


urlpatterns = [
    url(
        r'^$',
        ChatterBotView.as_view(),
        name='chatterbot',
    ),
]

chatbot/chatbot/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from chatterbot.ext.django_chatterbot import urls as chatterbot_urls
from chatbot.views import ChatterBotAppView

app_name = "chatterbot"

# urlpatterns = [
#     url(r'^chatterbot/', include('chatterbot.ext.django_chatterbot.urls', namespace='chatterbot'))
#]
urlpatterns = [
    url(r'^$', ChatterBotAppView.as_view(), name='main'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^api/chatterbot/', include((chatterbot_urls, app_name), namespace='chatterbot')),
]

chatbot/chatbot/chatterbot/ext/django_chatterbot/models.py
from django.db import models
from django.utils import timezone


class Statement(models.Model):
    """
    A statement represents a single spoken entity, sentence or
    phrase that someone can say.
    """

    text = models.CharField(
        unique=True,
        blank=False,
        null=False,
        max_length=255
    )

    created_at = models.DateTimeField(
        default=timezone.now,
        help_text='The date and time that this statement was created at.'
    )

    extra_data = models.CharField(max_length=500)

    # This is the confidence with which the chat bot believes
    # this is an accurate response. This value is set when the
    # statement is returned by the chat bot.
    confidence = 0

    def __str__(self):
        if len(self.text.strip()) > 60:
            return '{}...'.format(self.text[:57])
        elif len(self.text.strip()) > 0:
            return self.text
        return '<empty>'

    def __init__(self, *args, **kwargs):
        super(Statement, self).__init__(*args, **kwargs)

        # Responses to be saved if the statement is updated with the storage adapter
        self.response_statement_cache = []

    @property
    def in_response_to(self):
        """
        Return the response objects that are for this statement.
        """
        return Response.objects.filter(statement=self)

    def add_extra_data(self, key, value):
        """
        Add extra data to the extra_data field.
        """
        import json

        if not self.extra_data:
            self.extra_data = '{}'

        extra_data = json.loads(self.extra_data)
        extra_data[key] = value

        self.extra_data = json.dumps(extra_data)

    def add_response(self, statement):
        """
        Add a response to this statement.
        """
        self.response_statement_cache.append(statement)

    def remove_response(self, response_text):
        """
        Removes a response from the statement's response list based
        on the value of the response text.

        :param response_text: The text of the response to be removed.
        :type response_text: str
        """
        is_deleted = False
        response = self.in_response.filter(response__text=response_text)

        if response.exists():
            is_deleted = True

        return is_deleted

    def get_response_count(self, statement):
        """
        Find the number of times that the statement has been used
        as a response to the current statement.

        :param statement: The statement object to get the count for.
        :type statement: chatterbot.conversation.statement.Statement

        :returns: Return the number of times the statement has been used as a response.
        :rtype: int
        """
        try:
            response = self.in_response.get(response__text=statement.text)
            return response.occurrence
        except Response.DoesNotExist:
            return 0

    def serialize(self):
        """
        :returns: A dictionary representation of the statement object.
        :rtype: dict
        """
        import json
        data = {}

        if not self.extra_data:
            self.extra_data = '{}'

        data['text'] = self.text
        data['in_response_to'] = []
        data['created_at'] = self.created_at
        data['extra_data'] = json.loads(self.extra_data)

        for response in self.in_response.all():
            data['in_response_to'].append(response.serialize())

        return data


class Response(models.Model):
    """
    Connection between a response and the statement that triggered it.

    Comparble to a ManyToMany "through" table, but without the M2M indexing/relations.
    The text and number of times the response has occurred are stored.
    """

    statement = models.ForeignKey(
        'Statement',
        related_name='in_response'
    )

    response = models.ForeignKey(
        'Statement',
        related_name='responses'
    )

    unique_together = (('statement', 'response'),)

    occurrence = models.PositiveIntegerField(default=1)

    def __str__(self):
        statement = self.statement.text
        response = self.response.text
        return '{} => {}'.format(
            statement if len(statement) <= 20 else statement[:17] + '...',
            response if len(response) <= 40 else response[:37] + '...'
        )

    def serialize(self):
        """
        :returns: A dictionary representation of the statement object.
        :rtype: dict
        """
        data = {}

        data['text'] = self.response.text
        data['occurrence'] = self.occurrence

        return data


class Conversation(models.Model):
    """
    A sequence of statements representing a conversation.
    """

    statements = models.ManyToManyField(
        'Statement',
        related_name='conversation',
        help_text='The statements in this conversation.'
    )

    def __str__(self):
        return str(self.id)

chatbot/chatbot/chatterbot/ext/django_chatterbot/views.py
import json
from django.views.generic import View
from django.http import JsonResponse
from chatterbot import ChatBot
from chatterbot.ext.django_chatterbot import settings


class ChatterBotViewMixin(object):
    """
    Subclass this mixin for access to the 'chatterbot' attribute.
    """

    chatterbot = ChatBot(**settings.CHATTERBOT)

    def validate(self, data):
        """
        Validate the data recieved from the client.

        * The data should contain a text attribute.
        """
        from django.core.exceptions import ValidationError

        if 'text' not in data:
            raise ValidationError('The attribute "text" is required.')

    def get_chat_session(self, request):
        """
        Return the current session for the chat if one exists.
        Create a new session if one does not exist.
        """
        chat_session_id = request.session.get('chat_session_id', None)
        chat_session = self.chatterbot.conversation_sessions.get(chat_session_id, None)

        if not chat_session:
            chat_session = self.chatterbot.conversation_sessions.new()
            request.session['chat_session_id'] = chat_session.id_string

        return chat_session


class ChatterBotView(ChatterBotViewMixin, View):
    """
    Provide an API endpoint to interact with ChatterBot.
    """

    def _serialize_conversation(self, session):
        if session.conversation.empty():
            return []

        conversation = []

        for statement, response in session.conversation:
            conversation.append([statement.serialize(), response.serialize()])

        return conversation

    def post(self, request, *args, **kwargs):
        """
        Return a response to the statement in the posted data.
        """
        input_data = json.loads(request.read().decode('utf-8'))

        self.validate(input_data)

        chat_session = self.get_chat_session(request)

        response = self.chatterbot.get_response(input_data, chat_session.id_string)
        response_data = response.serialize()

        return JsonResponse(response_data, status=200)

    def get(self, request, *args, **kwargs):
        """
        Return data corresponding to the current conversation.
        """
        chat_session = self.get_chat_session(request)

        data = {
            'detail': 'You should make a POST request to this endpoint.',
            'name': self.chatterbot.name,
            'conversation': self._serialize_conversation(chat_session)
        }

        # Return a method not allowed response
        return JsonResponse(data, status=405)

    def patch(self, request, *args, **kwargs):
        """
        The patch method is not allowed for this endpoint.
        """
        data = {
            'detail': 'You should make a POST request to this endpoint.'
        }

        # Return a method not allowed response
        return JsonResponse(data, status=405)

    def delete(self, request, *args, **kwargs):
        """
        The delete method is not allowed for this endpoint.
        """
        data = {
            'detail': 'You should make a POST request to this endpoint.'
        }

        # Return a method not allowed response
        return JsonResponse(data, status=405)

chatbot/chatbot/views.py
from django.views.generic.base import TemplateView


class ChatterBotAppView(TemplateView):
    template_name = "app.html"

chatbot/chatbot/templates/app.html
{% load staticfiles %}
<!doctype html>
<html>
  <head>
    <title>Django ChatterBot Example</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}"/>
  </head>
  <body>

    {% include 'nav.html' %}

    <div class="container">

      <div class="jumbotron mt-1">
        <h1 class="jumbotron-heading text-xs-center">ChatterBot</h1>
        <p class="lead text-xs-center">
          This is a web app that allows you to talk to ChatterBot.
        </p>

        <hr class="my-2">

        <div class="row">
          <div class="col-xs-6 offset-xs-3">
            <ul class="list-group chat-log js-chat-log">
            </ul>

            <div class="input-group input-group-lg mt-1">
              <input type="text" class="form-control js-text" placeholder="Type something to begin..."/>
              <span class="input-group-btn">
                <button class="btn btn-primary js-say">Submit</button>
              </span>
            </div>
            
          </div>
        </div>

      </div>

    </div>

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/js.cookie.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script>
      var chatterbotUrl = '{% url "chatterbot:chatterbot" %}';
      var csrftoken = Cookies.get('csrftoken');

      function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }

      $.ajaxSetup({
        beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
        }
      });

      var $chatlog = $('.js-chat-log');
      var $input = $('.js-text');
      var $sayButton = $('.js-say');

      function createRow(text) {
        var $row = $('<li class="list-group-item"></li>');

        $row.text(text);
        $chatlog.append($row);
      }

      function submitInput() {
        var inputData = {
          'text': $input.val()
        }

        // Display the user's input on the web page
        createRow(inputData.text);

        var $submit = $.ajax({
          type: 'POST',
          url: chatterbotUrl,
          data: JSON.stringify(inputData),
          contentType: 'application/json',
          dataType: 'json'
        });

        $submit.done( function(statement) {
            //var $stmt = $.parseJSON(statement);
            createRow(statement.text);
            // Clear the input field
            $input.val('');
            // Scroll to the bottom of the chat interface
            $chatlog[0].scrollTop = $chatlog[0].scrollHeight;
        });

        $submit.fail(function() {
          // TODO: Handle errors
        });
      }

      $sayButton.click(function() {
        submitInput();
      });

      $input.keydown(function(event) {
          // Submit the input when the enter button is pressed
        if (event.keyCode == 13) {
          submitInput();
        }
      });
    </script>
  </body>
</html>

chatbot/chatbot/templates/nav.html
{% load staticfiles %}

<nav class="navbar navbar-dark bg-inverse navbar-full">

  <a class="navbar-brand" href="{% url 'main' %}">
    <img src="{% static 'img/chatterbot.png' %}" width="30" height="30" class="d-inline-block align-top" alt="ChatterBot">
    ChatterBot
  </a>

  <ul class="nav navbar-nav">
   <!--  <li class="nav-item">
      <a class="nav-link" href="http://chatterbot.readthedocs.io/en/stable/">Documentation</a>
    </li> -->
    <li class="nav-item">
      <a class="nav-link" href="https://github.com/Surendhar95/chatbot">GitHub</a>
    </li>
  </ul>

  <ul class="nav navbar-nav float-xs-right">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'admin:index' %}">Django Admin</a>
    </li>
  </ul>
</nav>